# Generated by Django 5.2.9 on 2026-02-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_review_date_alter_login_viewpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
